function y = Gaussian_Function(x, a, b, c)
    %% -------------------------------------------------------------------------
    %%
    %% Function: Gaussian_Function(x, a, b, c)
    %%
    %% -------------------------------------------------------------------------
    %
    %% Use:
    %       - y = Gaussian_Function(x, a, b, c)
    %
    %% Description:
    %       This function returns the value of a Gaussian function at a given
    %       point x, or at a set of points x.
    %
    %% Function parameters:
    %       - x:    Point(s) at which the Gaussian function is evaluated.
    %       - a:    Amplitude of the Gaussian function.
    %       - b:    Mean of the Gaussian function.
    %       - c:    Standard deviation of the Gaussian function.
    %
    %% Examples:
    %       - y = Gaussian_Function(0, 1, 0, 1)
    %       - y = Gaussian_Function([0, 1, 2], 1, 0, 1)
    %
    %% Copyright (C) 2023 Ljubomir Kurij <ljubomir_kurij@protonmail.com>
    %
    %% -------------------------------------------------------------------------
    fname = 'Gaussian_Function';
    use_case_a = sprintf(' - y = %s(x, a, b, c)', fname);

    % Check input arguments ----------------------------------------------------

    % Check number of input arguments
    if 4 ~= nargin
        error( ...
              'Invalid call to %s. Correct usage is:\n%s', ...
              fname, ...
              use_case_a ...
             );
    end  % End of if 4 ~= nargin

    % Check the type of the input arguments
    validateattributes( ...
                       x, ...
                       {'numeric'}, ...
                       {'nonempty', 'nonnan', 'finite', 'real', 'vector'}, ...
                       fname, ...
                       'x' ...
                      );
    validateattributes( ...
                       a, ...
                       {'numeric'}, ...
                       {'nonempty', 'nonnan', 'finite', 'real', 'scalar'}, ...
                       fname, ...
                       'a' ...
                      );
    validateattributes( ...
                       b, ...
                       {'numeric'}, ...
                       {'nonempty', 'nonnan', 'finite', 'real', 'scalar'}, ...
                       fname, ...
                       'b' ...
                      );
    validateattributes( ...
                       c, ...
                       {'numeric'}, ...
                       {'nonempty', 'nonnan', 'finite', 'real', 'scalar'}, ...
                       fname, ...
                       'c' ...
                      );

    % Do the calculation -------------------------------------------------------
    y = a .* exp(-((x - b).^2) ./ (2 * c^2));

end  % End of function Gaussian_Function

% End of file 'Gaussian_Function.m'
