function y = Gaussian_Signal(x, a, b, c, nvar)
    %% -------------------------------------------------------------------------
    %%
    %% Function: Gaussian_Signal(x, a, b, c, nvar)
    %%
    %% -------------------------------------------------------------------------
    %
    %% Use:
    %       - y = Gaussian_Signal(x, a, b, c, nvar)
    %
    %% Description:
    %       For the given abscissa x, and the parameters a, b, and c, this
    %       function returns the value of a Gaussian function at a given
    %       point x, or at a set of points x, with a Gaussian noise of
    %       variance nvar.
    %
    %% Function parameters:
    %       - x:    point(s) at which the Gaussian function is evaluated.
    %       - a:    amplitude of the Gaussian function.
    %       - b:    mean of the Gaussian function.
    %       - c:    standard deviation of the Gaussian function.
    %       - nvar: variance of the Gaussian noise.
    %
    %% Examples:
    %       - y = Gaussian_Function(0, 1, 0, 1, 0)
    %       - y = Gaussian_Function([0, 1, 2], 1, 0, 1, 1)
    %
    %% Copyright (C) 2023 Ljubomir Kurij <ljubomir_kurij@protonmail.com>
    %
    %% -------------------------------------------------------------------------
    fname = 'Gaussian_Signal';
    use_case_a = sprintf(' - y = %s(x, a, b, c, nvar)', fname);

    % Check input arguments ----------------------------------------------------

    % Check number of input arguments
    if 5 ~= nargin
        error( ...
              'Invalid call to %s. Correct usage is:\n%s', ...
              fname, ...
              use_case_a ...
             );
    end  % End of if 5 ~= nargin

    % Check the type of the input arguments
    validateattributes( ...
                       x, ...
                       {'numeric'}, ...
                       {'nonempty', 'nonnan', 'finite', 'real', 'vector'}, ...
                       fname, ...
                       'x' ...
                      );
    validateattributes( ...
                       a, ...
                       {'numeric'}, ...
                       {'nonempty', 'nonnan', 'finite', 'real', 'scalar'}, ...
                       fname, ...
                       'a' ...
                      );
    validateattributes( ...
                       b, ...
                       {'numeric'}, ...
                       {'nonempty', 'nonnan', 'finite', 'real', 'scalar'}, ...
                       fname, ...
                       'b' ...
                      );
    validateattributes( ...
                       c, ...
                       {'numeric'}, ...
                       {'nonempty', 'nonnan', 'finite', 'real', 'scalar'}, ...
                       fname, ...
                       'c' ...
                      );
    validateattributes( ...
                       nvar, ...
                       {'numeric'}, ...
                       { ...
                        'nonempty', ...
                        'nonnan', ...
                        'finite', ...
                        'real', ...
                        'scalar', ...
                        '>=', 0}, ...
                       fname, ...
                       'nvar' ...
                      );

    % Do the calculation -------------------------------------------------------
    y = Gaussian_Function(x, a, b, c);

    % Add Gaussian noise if noise variance is not zero
    if 0 ~= nvar
        y = y + sqrt(nvar) * randn(size(y));
    end  % End of if 0 ~= nvar

end  % End of function 'Gaussian_Signal'

% End of file 'Gaussian_Signal.m'