function l = logistic_function(x, L, k, x0)
%% -----------------------------------------------------------------------------
%%
%% Function: logistic_function(x, L, k, x0)
%%
%% -----------------------------------------------------------------------------
%
%% Use:
%       - l = logistic_function(x, L, k, x0)
%
%% Description:
%       Compute the logistic function
%
%% Function parameters:
%       - x:    x values
%       - L:    maximum value
%       - k:    steepness
%       - x0:   x value of the sigmoid's midpoint
%
%% Examples:
%       - l = logisitc_function(x, L, k, x0)
%
%% (C) Copyright 2023 Ljubomir Kurij
%
%% -----------------------------------------------------------------------------
    fname = 'logistic_function';
    use_case_a = sprintf('%s(x, L, k, x0)', fname);

    % Check input arguments ----------------------------------------------------

    % Check the number of input arguments
    if 4 ~= nargin
        error( ...
              'Invalid call to %s. Correct usage is:\n%s', ...
              fname, ...
              use_case_a ...
             );
    end  % End of if 4 ~= nargin

    % Check the type of input arguments
    validateattributes(
                       x, ...
                       {'numeric'}, ...
                       % {'vector', 'nonempty', 'real', 'finite'}, ...
                       {'nonempty', 'real', 'finite'}, ...
                       fname, ...
                       'x' ...
                      );
    validateattributes(
                       L, ...
                       {'numeric'}, ...
                       {'scalar', 'nonempty', 'real', 'finite', '>', 0}, ...
                       fname, ...
                       'L' ...
                      );
    validateattributes(
                       k, ...
                       {'numeric'}, ...
                       {'scalar', 'nonempty', 'real', 'finite'}, ...
                       fname, ...
                       'k' ...
                      );
    validateattributes(
                       x0, ...
                       {'numeric'}, ...
                       {'scalar', 'nonempty', 'real', 'finite'}, ...
                       fname, ...
                       'x0' ...
                      );

    % Do the calculations ------------------------------------------------------

    % NOTE: To determine the steepness of the curve, gor the given width of the
    %       curve, use the following formula:
    %           k = 2*log(95/5)/width

    l = L./(1 + exp(-k*(x-x0)));

end  % End of function logistic_function

% End of file 'logistic_function.m'